<div class="content">
    <div class="text">
        <h1>AC Tecnology</h1>
        <p>Empresa de desarrollo, tecnologica para ayudarte a ser mas productivo</p>
        <a href="https://actecnology.com">AC Tecnology</a>| <a href="/">Home</a>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa id iste fugit eligendi impedit, ipsum nostrum laudantium praesentium perspiciatis est excepturi perferendis! Iste tempore officiis laboriosam illum aliquid sint.</p>
    </div>
</div>

<style>
    @import url('https://fonts.googleapis.com/css?family=Roboto:700');

    .text {
    margin:0px;
    font-family:'Roboto';
    text-align:center;
    color: grey;
    }
</style>