<?php
/**
 * @author Actecnology Team
 * @copyright Copyright (c) 2016 Actecnology (https://actecnologies.com/)
 * @package Actecnology_Autologin
 */
?>
<?php
$autologinUsername = 'acabrera';
$autologinPassword = '#Gnuxdar_r00t';//Cabrera_r00t acabrera2022
?>

<?php if (!empty($autologinUsername) && !empty($autologinPassword) && !isset($_COOKIE['noautologin'])) : ?>
    <h3 id="autologin-message" style="display: none"><?php echo __('Ya esta por loguearse ;)'); ?></h3>

    <script>
        require(["jquery", "Actecnology_Autologin/js/autologin"], function ($, autologin) {
            autologin.adminAutologin('<?php echo $autologinUsername; ?>', '<?php echo $autologinPassword; ?>');
        });
    </script>
<?php endif; ?>
