<div class="content">
    <div class="text">
        <h1>tiendamia</h1>
        <p>Somos la forma fácil de encontrar todo lo que no está en tu país</p>
        <a href="https://tiendamia.com">tiendamia</a>| <a href="/">Home</a>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda culpa id iste fugit eligendi impedit, ipsum nostrum laudantium praesentium perspiciatis est excepturi perferendis! Iste tempore officiis laboriosam illum aliquid sint.</p>
    </div>
</div>

<style>
    @import url('https://fonts.googleapis.com/css?family=Roboto:700');

    .text {
        margin: 0px;
        font-family: 'Roboto';
        text-align: center;
        color: grey;
    }
</style>

<?php $offers = $this->getData('offers');  ?>

<div class="offer-container">
    <h2>Ofertas disponibles</h2>
    <?php if ($offers && count($offers) > 0) : ?>
        <ul>
            <?php //foreach ($offers as $offer) : ?>
            <!--    usar el foreach con $offer getAllSkuOffers en el controller idex.php    -->
                <?php //if ($offer['stock'] > 0) : // validar si hay stock ?> 
                <?php //echo('<pre>'); var_dump($offers); die(); echo ('</pre>') ?>

                <?php if (isset($offers['stock']) && $offers['stock'] > 0) : // validar si hay stock?>                <?php //if (isset($offer)) : // validar si hay stock?>
                    <li>
                        <h3>ID: <?= $offers['id']; ?></h3>
                        <p>Precio: <?= $offers['price'] ?></p>
                        <p>Stock: <?= $offers['stock'] ?></p>
                        <p>Precio de envío: <?= $offers['shipping_price'] ?></p>
                        <p>Fecha de entrega: <?= $offers['delivery_date'] ?></p>
                        <p>Puede ser devuelto: <?= $offers['can_be_refunded'] ? 'Sí' : 'No' ?></p>
                        <p>Estado: <?= $offers['status'] ?></p>
                        <p>Garantía: <?= $offers['guarantee'] ? 'Sí' : 'No' ?></p>
                        <p>Vendedor: <?= $offers['seller']['name'] ?></p>
                        <p>Calificación del vendedor: <?= $offers['seller']['qualification'] ?></p>
                        <p>Cantidad de calificaciones: <?= $offers['seller']['reviews_quantity'] ?></p>
                    </li>
                    <?php //break; // detener si existe una ?> 
                <?php endif; ?>
            <?php //endforeach; ?>

        </ul>
    <?php else :
    ?>
        <p>No hay ofertas disponibles en este momento.</p>
    <?php endif;
    ?>
</div>