<?php

/** @var \Actecnology\SaleSku\Block\Adminhtml\DailyReport\Index $block */
$salesData = $block->getSalesData();
?>
<?php
echo "<pre>";
var_dump($salesData);
echo "</pre>";


?>
<?php if (!empty($salesData)) : ?>
    <table>
        <thead>
            <tr>
                <th>SKU</th>
                <th>Total de Ventas</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($salesData as $sku => $totalSales) : ?>
                <tr>
                    <td><?= $sku ?></td>
                    <td><?= $totalSales ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else : ?>
    <p>No hay ventas disponibles.</p>
<?php endif; ?>